<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260401100527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE card_history_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, name_fr VARCHAR(100) DEFAULT NULL, name_en VARCHAR(100) DEFAULT NULL, name_it VARCHAR(100) DEFAULT NULL, name_es VARCHAR(100) DEFAULT NULL, name_de VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E4964378AEA34913 ON card_history_status (reference)');
        $this->addSql('ALTER TABLE card ADD card_history_status_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D3FE9BD68B FOREIGN KEY (card_history_status_id) REFERENCES card_history_status (id)');
        $this->addSql('CREATE INDEX IDX_161498D3FE9BD68B ON card (card_history_status_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE card_history_status');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D3FE9BD68B');
        $this->addSql('DROP INDEX IDX_161498D3FE9BD68B');
        $this->addSql('ALTER TABLE card DROP card_history_status_id');
    }
}
