<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260403065736 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE card_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, main_cost INT DEFAULT NULL, recall_cost INT DEFAULT NULL, ocean_power INT DEFAULT NULL, mountain_power INT DEFAULT NULL, forest_power INT DEFAULT NULL, echo_effect TEXT DEFAULT NULL, permanent VARCHAR(255) DEFAULT NULL, is_banned BOOLEAN NOT NULL, is_errated BOOLEAN NOT NULL, is_suspended BOOLEAN NOT NULL, deck_limit INT NOT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, faction_id INT DEFAULT NULL, card_type_id INT DEFAULT NULL, effect1_id INT DEFAULT NULL, effect2_id INT DEFAULT NULL, effect3_id INT DEFAULT NULL, card_history_status_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_55F4B503989D9B62 ON card_group (slug)');
        $this->addSql('CREATE INDEX IDX_55F4B50367922D0F ON card_group (effect1_id)');
        $this->addSql('CREATE INDEX IDX_55F4B503752782E1 ON card_group (effect2_id)');
        $this->addSql('CREATE INDEX IDX_55F4B503CD9BE584 ON card_group (effect3_id)');
        $this->addSql('CREATE INDEX IDX_55F4B503FE9BD68B ON card_group (card_history_status_id)');
        $this->addSql('CREATE INDEX idx_card_group_slug ON card_group (slug)');
        $this->addSql('CREATE INDEX idx_card_group_faction ON card_group (faction_id)');
        $this->addSql('CREATE INDEX idx_card_group_card_type ON card_group (card_type_id)');
        $this->addSql('CREATE INDEX idx_card_group_main_cost ON card_group (main_cost)');
        $this->addSql('CREATE INDEX idx_card_group_recall_cost ON card_group (recall_cost)');
        $this->addSql('CREATE TABLE card_group_sub_type_link (card_group_id INT NOT NULL, card_sub_type_id INT NOT NULL, PRIMARY KEY (card_group_id, card_sub_type_id))');
        $this->addSql('CREATE INDEX IDX_D4C1A094476517C4 ON card_group_sub_type_link (card_group_id)');
        $this->addSql('CREATE INDEX IDX_D4C1A0945D408FFD ON card_group_sub_type_link (card_sub_type_id)');
        $this->addSql('CREATE TABLE card_group_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, name VARCHAR(100) DEFAULT NULL, main_effect TEXT DEFAULT NULL, echo_effect TEXT DEFAULT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, card_group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_92F4DF7A476517C4 ON card_group_translation (card_group_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_92F4DF7A476517C44180C698 ON card_group_translation (card_group_id, locale)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B5034448F8DA FOREIGN KEY (faction_id) REFERENCES faction (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B503925606E5 FOREIGN KEY (card_type_id) REFERENCES card_type (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B50367922D0F FOREIGN KEY (effect1_id) REFERENCES main_effect (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B503752782E1 FOREIGN KEY (effect2_id) REFERENCES main_effect (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B503CD9BE584 FOREIGN KEY (effect3_id) REFERENCES main_effect (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B503FE9BD68B FOREIGN KEY (card_history_status_id) REFERENCES card_history_status (id)');
        $this->addSql('ALTER TABLE card_group_sub_type_link ADD CONSTRAINT FK_D4C1A094476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE card_group_sub_type_link ADD CONSTRAINT FK_D4C1A0945D408FFD FOREIGN KEY (card_sub_type_id) REFERENCES card_sub_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE card_group_translation ADD CONSTRAINT FK_92F4DF7A476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card ADD variation VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE card ADD card_group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D3476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_card_altered_id ON card (altered_id)');
        $this->addSql('CREATE INDEX idx_card_card_group ON card (card_group_id)');
        $this->addSql('CREATE INDEX idx_card_card_number ON card (card_number)');
        $this->addSql('CREATE INDEX idx_card_is_serialized ON card (is_serialized)');
        $this->addSql('ALTER INDEX reference RENAME TO idx_card_reference');
        $this->addSql('ALTER INDEX idx_161498d310fb0d18 RENAME TO idx_card_set');
        $this->addSql('ALTER INDEX idx_161498d3f3747573 RENAME TO idx_card_rarity');
        $this->addSql('ALTER TABLE card_ruling ADD card_group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE card_ruling ALTER card_id DROP NOT NULL');
        $this->addSql('ALTER TABLE card_ruling ADD CONSTRAINT FK_AA7B3B64476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_AA7B3B64476517C4 ON card_ruling (card_group_id)');
        $this->addSql('DROP INDEX uniq_8cabe71d4acc9a20ac10a1214180c698');
        $this->addSql('ALTER TABLE lore_entry ADD card_group_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lore_entry ALTER card_id DROP NOT NULL');
        $this->addSql('ALTER TABLE lore_entry ADD CONSTRAINT FK_8CABE71D476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8CABE71D476517C4 ON lore_entry (card_group_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_lore_entry_group ON lore_entry (card_group_id, altered_id, locale)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B5034448F8DA');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B503925606E5');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B50367922D0F');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B503752782E1');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B503CD9BE584');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B503FE9BD68B');
        $this->addSql('ALTER TABLE card_group_sub_type_link DROP CONSTRAINT FK_D4C1A094476517C4');
        $this->addSql('ALTER TABLE card_group_sub_type_link DROP CONSTRAINT FK_D4C1A0945D408FFD');
        $this->addSql('ALTER TABLE card_group_translation DROP CONSTRAINT FK_92F4DF7A476517C4');
        $this->addSql('DROP TABLE card_group');
        $this->addSql('DROP TABLE card_group_sub_type_link');
        $this->addSql('DROP TABLE card_group_translation');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D3476517C4');
        $this->addSql('DROP INDEX idx_card_altered_id');
        $this->addSql('DROP INDEX idx_card_card_group');
        $this->addSql('DROP INDEX idx_card_card_number');
        $this->addSql('DROP INDEX idx_card_is_serialized');
        $this->addSql('ALTER TABLE card DROP variation');
        $this->addSql('ALTER TABLE card DROP card_group_id');
        $this->addSql('ALTER INDEX idx_card_set RENAME TO idx_161498d310fb0d18');
        $this->addSql('ALTER INDEX idx_card_reference RENAME TO reference');
        $this->addSql('ALTER INDEX idx_card_rarity RENAME TO idx_161498d3f3747573');
        $this->addSql('ALTER TABLE card_ruling DROP CONSTRAINT FK_AA7B3B64476517C4');
        $this->addSql('DROP INDEX IDX_AA7B3B64476517C4');
        $this->addSql('ALTER TABLE card_ruling DROP card_group_id');
        $this->addSql('ALTER TABLE card_ruling ALTER card_id SET NOT NULL');
        $this->addSql('ALTER TABLE lore_entry DROP CONSTRAINT FK_8CABE71D476517C4');
        $this->addSql('DROP INDEX IDX_8CABE71D476517C4');
        $this->addSql('DROP INDEX uniq_lore_entry_group');
        $this->addSql('ALTER TABLE lore_entry DROP card_group_id');
        $this->addSql('ALTER TABLE lore_entry ALTER card_id SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_8cabe71d4acc9a20ac10a1214180c698 ON lore_entry (card_id, altered_id, locale)');
    }
}
