<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260401094123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE card_ruling (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, content JSON NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA7B3B644ACC9A20 ON card_ruling (card_id)');
        $this->addSql('CREATE TABLE lore_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, content JSON NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8CABE71D4ACC9A20 ON lore_entry (card_id)');
        $this->addSql('ALTER TABLE card_ruling ADD CONSTRAINT FK_AA7B3B644ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lore_entry ADD CONSTRAINT FK_8CABE71D4ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card ADD is_banned BOOLEAN NOT NULL DEFAULT FALSE');
        $this->addSql('ALTER TABLE card ADD is_errated BOOLEAN NOT NULL DEFAULT FALSE');
        $this->addSql('ALTER TABLE card ADD is_suspended BOOLEAN NOT NULL DEFAULT FALSE');
        $this->addSql('ALTER TABLE card ADD is_ownerless BOOLEAN NOT NULL DEFAULT FALSE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE card_ruling DROP CONSTRAINT FK_AA7B3B644ACC9A20');
        $this->addSql('ALTER TABLE lore_entry DROP CONSTRAINT FK_8CABE71D4ACC9A20');
        $this->addSql('DROP TABLE card_ruling');
        $this->addSql('DROP TABLE lore_entry');
        $this->addSql('ALTER TABLE card DROP is_banned');
        $this->addSql('ALTER TABLE card DROP is_errated');
        $this->addSql('ALTER TABLE card DROP is_suspended');
        $this->addSql('ALTER TABLE card DROP is_ownerless');
    }
}
