<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260421183100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ability_condition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, altered_id INT NOT NULL, text_fr TEXT DEFAULT NULL, text_en TEXT DEFAULT NULL, text_it TEXT DEFAULT NULL, text_es TEXT DEFAULT NULL, text_de TEXT DEFAULT NULL, is_support BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_29ACCEFFAC10A121 ON ability_condition (altered_id)');
        $this->addSql('CREATE INDEX idx_ability_condition_altered_id ON ability_condition (altered_id)');
        $this->addSql('CREATE TABLE ability_effect (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, altered_id INT NOT NULL, text_fr TEXT DEFAULT NULL, text_en TEXT DEFAULT NULL, text_it TEXT DEFAULT NULL, text_es TEXT DEFAULT NULL, text_de TEXT DEFAULT NULL, is_support BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A06EB43CAC10A121 ON ability_effect (altered_id)');
        $this->addSql('CREATE INDEX idx_ability_effect_altered_id ON ability_effect (altered_id)');
        $this->addSql('CREATE TABLE ability_trigger (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, altered_id INT NOT NULL, text_fr TEXT DEFAULT NULL, text_en TEXT DEFAULT NULL, text_it TEXT DEFAULT NULL, text_es TEXT DEFAULT NULL, text_de TEXT DEFAULT NULL, is_support BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_66A1EECFAC10A121 ON ability_trigger (altered_id)');
        $this->addSql('CREATE INDEX idx_ability_trigger_altered_id ON ability_trigger (altered_id)');
        $this->addSql('CREATE TABLE artist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(150) NOT NULL, name VARCHAR(150) NOT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_artist_reference ON artist (reference)');
        $this->addSql('CREATE TABLE card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, altered_id VARCHAR(50) NOT NULL, card_number INT NOT NULL, collector_number_formated_id VARCHAR(50) DEFAULT NULL, img_path VARCHAR(255) DEFAULT NULL, downloaded_img_path VARCHAR(255) DEFAULT NULL, all_image_path JSON NOT NULL, assets JSON DEFAULT NULL, qr_url_detail VARCHAR(255) DEFAULT NULL, kickstarter BOOLEAN NOT NULL, promo BOOLEAN NOT NULL, transfuge BOOLEAN NOT NULL, is_serialized BOOLEAN NOT NULL, is_parent_serialized BOOLEAN NOT NULL, is_ownerless BOOLEAN NOT NULL, variation VARCHAR(50) DEFAULT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, card_group_id INT DEFAULT NULL, rarity_id INT DEFAULT NULL, set_id INT DEFAULT NULL, parent_card_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_161498D33884EE66 ON card (parent_card_id)');
        $this->addSql('CREATE INDEX idx_card_reference ON card (reference)');
        $this->addSql('CREATE INDEX idx_card_altered_id ON card (altered_id)');
        $this->addSql('CREATE INDEX idx_card_set ON card (set_id)');
        $this->addSql('CREATE INDEX idx_card_rarity ON card (rarity_id)');
        $this->addSql('CREATE INDEX idx_card_card_group ON card (card_group_id)');
        $this->addSql('CREATE INDEX idx_card_card_number ON card (card_number)');
        $this->addSql('CREATE INDEX idx_card_is_serialized ON card (is_serialized)');
        $this->addSql('CREATE TABLE card_artist (card_id INT NOT NULL, artist_id INT NOT NULL, PRIMARY KEY (card_id, artist_id))');
        $this->addSql('CREATE INDEX IDX_7366C5F34ACC9A20 ON card_artist (card_id)');
        $this->addSql('CREATE INDEX IDX_7366C5F3B7970CF8 ON card_artist (artist_id)');
        $this->addSql('CREATE TABLE card_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(100) NOT NULL, main_cost INT DEFAULT NULL, recall_cost INT DEFAULT NULL, ocean_power INT DEFAULT NULL, mountain_power INT DEFAULT NULL, forest_power INT DEFAULT NULL, echo_effect TEXT DEFAULT NULL, permanent VARCHAR(255) DEFAULT NULL, is_banned BOOLEAN NOT NULL, is_errated BOOLEAN NOT NULL, is_suspended BOOLEAN NOT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, faction_id INT DEFAULT NULL, rarity_id INT DEFAULT NULL, card_type_id INT DEFAULT NULL, effect1_id INT DEFAULT NULL, effect2_id INT DEFAULT NULL, effect3_id INT DEFAULT NULL, card_history_status_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_55F4B503989D9B62 ON card_group (slug)');
        $this->addSql('CREATE INDEX IDX_55F4B503F3747573 ON card_group (rarity_id)');
        $this->addSql('CREATE INDEX IDX_55F4B50367922D0F ON card_group (effect1_id)');
        $this->addSql('CREATE INDEX IDX_55F4B503752782E1 ON card_group (effect2_id)');
        $this->addSql('CREATE INDEX IDX_55F4B503CD9BE584 ON card_group (effect3_id)');
        $this->addSql('CREATE INDEX IDX_55F4B503FE9BD68B ON card_group (card_history_status_id)');
        $this->addSql('CREATE INDEX idx_card_group_slug ON card_group (slug)');
        $this->addSql('CREATE INDEX idx_card_group_faction ON card_group (faction_id)');
        $this->addSql('CREATE INDEX idx_card_group_card_type ON card_group (card_type_id)');
        $this->addSql('CREATE INDEX idx_card_group_main_cost ON card_group (main_cost)');
        $this->addSql('CREATE INDEX idx_card_group_recall_cost ON card_group (recall_cost)');
        $this->addSql('CREATE INDEX idx_card_group_is_banned ON card_group (is_banned)');
        $this->addSql('CREATE INDEX idx_card_group_is_suspended ON card_group (is_suspended)');
        $this->addSql('CREATE INDEX idx_card_group_is_errated ON card_group (is_errated)');
        $this->addSql('CREATE INDEX idx_card_group_faction_rarity ON card_group (faction_id, rarity_id)');
        $this->addSql('CREATE TABLE card_group_sub_type_link (card_group_id INT NOT NULL, card_sub_type_id INT NOT NULL, PRIMARY KEY (card_group_id, card_sub_type_id))');
        $this->addSql('CREATE INDEX IDX_D4C1A094476517C4 ON card_group_sub_type_link (card_group_id)');
        $this->addSql('CREATE INDEX IDX_D4C1A0945D408FFD ON card_group_sub_type_link (card_sub_type_id)');
        $this->addSql('CREATE TABLE card_group_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, name VARCHAR(100) DEFAULT NULL, main_effect TEXT DEFAULT NULL, echo_effect TEXT DEFAULT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, card_group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_92F4DF7A476517C4 ON card_group_translation (card_group_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_92F4DF7A476517C44180C698 ON card_group_translation (card_group_id, locale)');
        $this->addSql('CREATE TABLE card_history_status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, name_fr VARCHAR(100) DEFAULT NULL, name_en VARCHAR(100) DEFAULT NULL, name_it VARCHAR(100) DEFAULT NULL, name_es VARCHAR(100) DEFAULT NULL, name_de VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E4964378AEA34913 ON card_history_status (reference)');
        $this->addSql('CREATE TABLE card_ruling (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, locale VARCHAR(8) DEFAULT NULL, event_format VARCHAR(50) DEFAULT NULL, ruling_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, card_group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA7B3B64476517C4 ON card_ruling (card_group_id)');
        $this->addSql('CREATE TABLE card_search (card_id INT NOT NULL, t1 INT DEFAULT NULL, c1 INT DEFAULT NULL, e1 INT DEFAULT NULL, t2 INT DEFAULT NULL, c2 INT DEFAULT NULL, e2 INT DEFAULT NULL, t3 INT DEFAULT NULL, c3 INT DEFAULT NULL, e3 INT DEFAULT NULL, has_effect BOOLEAN DEFAULT false NOT NULL, keywords TEXT[] NOT NULL DEFAULT \'{}\', PRIMARY KEY (card_id))');
        $this->addSql('CREATE TABLE card_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, altered_id VARCHAR(50) NOT NULL, name VARCHAR(75) NOT NULL, name_en VARCHAR(75) DEFAULT NULL, code VARCHAR(10) DEFAULT NULL, is_active BOOLEAN NOT NULL, reference VARCHAR(25) NOT NULL, illustration VARCHAR(255) DEFAULT NULL, illustration_path VARCHAR(255) DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, card_google_sheets JSON DEFAULT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_card_set_date ON card_set (date)');
        $this->addSql('CREATE TABLE card_sub_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, name_fr VARCHAR(100) DEFAULT NULL, name_en VARCHAR(100) DEFAULT NULL, name_it VARCHAR(100) DEFAULT NULL, name_es VARCHAR(100) DEFAULT NULL, name_de VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1279066BAEA34913 ON card_sub_type (reference)');
        $this->addSql('CREATE TABLE card_translation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(8) NOT NULL, name VARCHAR(50) NOT NULL, elements JSON NOT NULL, echo_effect TEXT DEFAULT NULL, main_effect TEXT DEFAULT NULL, collector_number_formated_id VARCHAR(50) DEFAULT NULL, img_path VARCHAR(255) DEFAULT NULL, downloaded_img_path VARCHAR(255) DEFAULT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, card_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_53BD1AF54ACC9A20 ON card_translation (card_id)');
        $this->addSql('CREATE TABLE card_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, name_fr VARCHAR(100) DEFAULT NULL, name_en VARCHAR(100) DEFAULT NULL, name_it VARCHAR(100) DEFAULT NULL, name_es VARCHAR(100) DEFAULT NULL, name_de VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_60ED558BAEA34913 ON card_type (reference)');
        $this->addSql('CREATE TABLE collection_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, collection_list_id UUID DEFAULT NULL, card_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C63B43D6982645A ON collection_card (collection_list_id)');
        $this->addSql('CREATE INDEX IDX_5C63B43D4ACC9A20 ON collection_card (card_id)');
        $this->addSql('CREATE TABLE collection_list (id UUID NOT NULL, deletedAt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, name VARCHAR(50) NOT NULL, public BOOLEAN NOT NULL, wanted_list BOOLEAN NOT NULL, trade_list BOOLEAN NOT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EBFD4F6A76ED395 ON collection_list (user_id)');
        $this->addSql('CREATE TABLE faction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, code VARCHAR(5) NOT NULL, position INT NOT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lore_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, altered_id VARCHAR(50) NOT NULL, locale VARCHAR(8) NOT NULL, type VARCHAR(50) DEFAULT NULL, elements JSON NOT NULL, card_group_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8CABE71D476517C4 ON lore_entry (card_group_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_lore_entry_group ON lore_entry (card_group_id, altered_id, locale)');
        $this->addSql('CREATE TABLE main_effect (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text_fr TEXT DEFAULT NULL, text_en TEXT DEFAULT NULL, text_it TEXT DEFAULT NULL, text_es TEXT DEFAULT NULL, text_de TEXT DEFAULT NULL, keywords JSON DEFAULT NULL, ability_key VARCHAR(30) DEFAULT NULL, ability_trigger_id INT DEFAULT NULL, ability_condition_id INT DEFAULT NULL, ability_effect_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_297C29E49D9E5937 ON main_effect (ability_trigger_id)');
        $this->addSql('CREATE INDEX IDX_297C29E452C0E4F7 ON main_effect (ability_condition_id)');
        $this->addSql('CREATE INDEX IDX_297C29E46193FE87 ON main_effect (ability_effect_id)');
        $this->addSql('CREATE INDEX idx_main_effect_ability_key ON main_effect (ability_key)');
        $this->addSql('CREATE INDEX idx_main_effect_text_en ON main_effect (text_en)');
        $this->addSql('CREATE INDEX idx_main_effect_text_fr ON main_effect (text_fr)');
        $this->addSql('CREATE TABLE rarity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(50) NOT NULL, name_fr VARCHAR(100) DEFAULT NULL, name_en VARCHAR(100) DEFAULT NULL, name_it VARCHAR(100) DEFAULT NULL, name_es VARCHAR(100) DEFAULT NULL, name_de VARCHAR(100) DEFAULT NULL, position INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B7C0BE46AEA34913 ON rarity (reference)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D3476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D3F3747573 FOREIGN KEY (rarity_id) REFERENCES rarity (id)');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D310FB0D18 FOREIGN KEY (set_id) REFERENCES card_set (id)');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D33884EE66 FOREIGN KEY (parent_card_id) REFERENCES card (id)');
        $this->addSql('ALTER TABLE card_artist ADD CONSTRAINT FK_7366C5F34ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE card_artist ADD CONSTRAINT FK_7366C5F3B7970CF8 FOREIGN KEY (artist_id) REFERENCES artist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B5034448F8DA FOREIGN KEY (faction_id) REFERENCES faction (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B503F3747573 FOREIGN KEY (rarity_id) REFERENCES rarity (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B503925606E5 FOREIGN KEY (card_type_id) REFERENCES card_type (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B50367922D0F FOREIGN KEY (effect1_id) REFERENCES main_effect (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B503752782E1 FOREIGN KEY (effect2_id) REFERENCES main_effect (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B503CD9BE584 FOREIGN KEY (effect3_id) REFERENCES main_effect (id)');
        $this->addSql('ALTER TABLE card_group ADD CONSTRAINT FK_55F4B503FE9BD68B FOREIGN KEY (card_history_status_id) REFERENCES card_history_status (id)');
        $this->addSql('ALTER TABLE card_group_sub_type_link ADD CONSTRAINT FK_D4C1A094476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE card_group_sub_type_link ADD CONSTRAINT FK_D4C1A0945D408FFD FOREIGN KEY (card_sub_type_id) REFERENCES card_sub_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE card_group_translation ADD CONSTRAINT FK_92F4DF7A476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card_ruling ADD CONSTRAINT FK_AA7B3B64476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card_translation ADD CONSTRAINT FK_53BD1AF54ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id)');
        $this->addSql('ALTER TABLE collection_card ADD CONSTRAINT FK_5C63B43D6982645A FOREIGN KEY (collection_list_id) REFERENCES collection_list (id)');
        $this->addSql('ALTER TABLE collection_card ADD CONSTRAINT FK_5C63B43D4ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id)');
        $this->addSql('ALTER TABLE collection_list ADD CONSTRAINT FK_EBFD4F6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE lore_entry ADD CONSTRAINT FK_8CABE71D476517C4 FOREIGN KEY (card_group_id) REFERENCES card_group (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE main_effect ADD CONSTRAINT FK_297C29E49D9E5937 FOREIGN KEY (ability_trigger_id) REFERENCES ability_trigger (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE main_effect ADD CONSTRAINT FK_297C29E452C0E4F7 FOREIGN KEY (ability_condition_id) REFERENCES ability_condition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE main_effect ADD CONSTRAINT FK_297C29E46193FE87 FOREIGN KEY (ability_effect_id) REFERENCES ability_effect (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D3476517C4');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D3F3747573');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D310FB0D18');
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D33884EE66');
        $this->addSql('ALTER TABLE card_artist DROP CONSTRAINT FK_7366C5F34ACC9A20');
        $this->addSql('ALTER TABLE card_artist DROP CONSTRAINT FK_7366C5F3B7970CF8');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B5034448F8DA');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B503F3747573');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B503925606E5');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B50367922D0F');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B503752782E1');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B503CD9BE584');
        $this->addSql('ALTER TABLE card_group DROP CONSTRAINT FK_55F4B503FE9BD68B');
        $this->addSql('ALTER TABLE card_group_sub_type_link DROP CONSTRAINT FK_D4C1A094476517C4');
        $this->addSql('ALTER TABLE card_group_sub_type_link DROP CONSTRAINT FK_D4C1A0945D408FFD');
        $this->addSql('ALTER TABLE card_group_translation DROP CONSTRAINT FK_92F4DF7A476517C4');
        $this->addSql('ALTER TABLE card_ruling DROP CONSTRAINT FK_AA7B3B64476517C4');
        $this->addSql('ALTER TABLE card_translation DROP CONSTRAINT FK_53BD1AF54ACC9A20');
        $this->addSql('ALTER TABLE collection_card DROP CONSTRAINT FK_5C63B43D6982645A');
        $this->addSql('ALTER TABLE collection_card DROP CONSTRAINT FK_5C63B43D4ACC9A20');
        $this->addSql('ALTER TABLE collection_list DROP CONSTRAINT FK_EBFD4F6A76ED395');
        $this->addSql('ALTER TABLE lore_entry DROP CONSTRAINT FK_8CABE71D476517C4');
        $this->addSql('ALTER TABLE main_effect DROP CONSTRAINT FK_297C29E49D9E5937');
        $this->addSql('ALTER TABLE main_effect DROP CONSTRAINT FK_297C29E452C0E4F7');
        $this->addSql('ALTER TABLE main_effect DROP CONSTRAINT FK_297C29E46193FE87');
        $this->addSql('DROP TABLE ability_condition');
        $this->addSql('DROP TABLE ability_effect');
        $this->addSql('DROP TABLE ability_trigger');
        $this->addSql('DROP TABLE artist');
        $this->addSql('DROP TABLE card');
        $this->addSql('DROP TABLE card_artist');
        $this->addSql('DROP TABLE card_group');
        $this->addSql('DROP TABLE card_group_sub_type_link');
        $this->addSql('DROP TABLE card_group_translation');
        $this->addSql('DROP TABLE card_history_status');
        $this->addSql('DROP TABLE card_ruling');
        $this->addSql('DROP TABLE card_search');
        $this->addSql('DROP TABLE card_set');
        $this->addSql('DROP TABLE card_sub_type');
        $this->addSql('DROP TABLE card_translation');
        $this->addSql('DROP TABLE card_type');
        $this->addSql('DROP TABLE collection_card');
        $this->addSql('DROP TABLE collection_list');
        $this->addSql('DROP TABLE faction');
        $this->addSql('DROP TABLE lore_entry');
        $this->addSql('DROP TABLE main_effect');
        $this->addSql('DROP TABLE rarity');
        $this->addSql('DROP TABLE "user"');
    }
}
